[project]
name = "xfeat_scm" #gets normalized to xfeat-scm
version = "0.1.0"
description = "Self-contained XFeat feature extraction model and corresponsing LighterGlue matcher."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python-headless >=4.10",
    "poselib",
    "kornia>=0.7.2",
    "tqdm",
    "gdown",
    "torch"
]


[tool.setuptools.package-data]
xfeat_scm = ["**/*.pt"]